routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// MEETUPS
Route::get('/', 'MeetupsController@index')->name('home');

Route::get('/get-balance', 'MeetupsController@getBalance');

Route::get('/login', 'MeetupsController@showLoginForm');
Route::post('/login', 'MeetupsController@login');
Route::get('/logout', 'MeetupsController@logout');

Route::get('/setting', 'MeetupsController@showSettingForm');
Route::post('/setting', 'MeetupsController@saveSetting');

Route::get('/subscribe', 'MeetupsController@showSubscribeForm');
Route::post('/subscribe', 'MeetupsController@subscribe');

Route::get('/claim', 'MeetupsController@showClaimForm');
Route::post('/claim', 'MeetupsController@claim');



// ADMIN
Route::middleware(['admin.login'])->namespace('Admin')->prefix('admin_ZwMTBv')->name('admin.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('user', 'UserController');

    Route::resource('transaction-info', 'TransactionInfoController');
});

resources/views/layouts/admin.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"/>

    <title>ZenCash Faucet Admin</title>

    @stack('styles')

</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{ route('admin.home') }}">
            Admin
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.user.index') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('admin.transaction-info.index') }}">Transaction Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ action('MeetupsController@logout') }}?t={{ time() }}">Logout
                        ({{ auth()->user()->username }})</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ action('MeetupsController@index') }}">Meetups</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container-fluid mt-2">

    @yield('content')

</div>


{{ Form::open(['method' => 'DELETE', 'class' => 'global-form-delete']) }}
{{ Form::close() }}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>

<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"
        integrity="sha256-km9ViEDg2jYMRIV3IgvhZkrGIXt7e+T0zYez9FC064c=" crossorigin="anonymous"></script>
<script>
    feather.replace()
</script>

<script>
    $(function () {

        $(".btn-delete").click(function () {
            var btn = $(this);
            if (confirm(btn.data("confirm"))) {
                var form = $(".global-form-delete");
                form.attr("action", btn.data("url"));
                form.submit();
            }
        });

        $(".date-range-picker").each(function (_, inputPicker) {
            inputPicker = $(inputPicker);

            inputPicker.daterangepicker({
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 3 Days': [moment().subtract(2, 'days'), moment()],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                    'This Year': [moment().startOf('year'), moment().endOf('year')],
                    'Last Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')]
                },
                autoUpdateInput: false,
                locale: {
                    cancelLabel: 'Clear'
                },
                showDropdowns: true
            }, function (start, end, label) {
                $(inputPicker.data("input-from")).val(start.format('YYYY-MM-DD'));
                $(inputPicker.data("input-to")).val(end.format('YYYY-MM-DD'));
            });

            inputPicker.on('apply.daterangepicker', function(ev, picker) {
                $(this).val(picker.startDate.format('MM/DD/YYYY') + ' => ' + picker.endDate.format('MM/DD/YYYY'));
            });

            inputPicker.on('cancel.daterangepicker', function(ev, picker) {
                inputPicker.val("");
                $(inputPicker.data("input-from")).val("");
                $(inputPicker.data("input-to")).val("");
            });
        });

    });
</script>

@stack('scripts')

</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto+Condensed:400,700" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous"/>

    <title>ZenCash</title>

    <style>
        body {
            background-image: url("{{ asset('assets/img/background_xs.png') }}");
            background-repeat: no-repeat;
            background-color: #0b284d;
            background-size: cover;
            background-position: center;
            width: 100vw;
            height: 100vh;
            color: white;
        }

        .title {
            font-size: 1.75rem;
            margin-bottom: 1.5rem;
            margin-top: 1.5rem;
            text-align: center;
            font-family: 'Roboto Condensed', sans-serif;
        }

        .camera-option {
            display: block;
            padding: 10px 0;
        }

        @media (min-width: 992px) {
            body {
                background-image: url("{{ asset('assets/img/background_md.png') }}");
            }

            .title {
                font-size: 2.75rem;
                margin-top: 2rem;
                margin-bottom: 3.5rem;
            }
        }

        a, a:hover {
            color: white;
        }

        .form-control, .input-group-text, .btn {
            border-radius: 0;
        }

        .modal, .modal a {
            color: #000;
        }

        .modal a.btn-success {
            color: white;
        }

        .karla {
            font-family: 'Karla', sans-serif;
        }
    </style>
    @stack('styles')

</head>
<body>

<!-- Page Content -->
<div class="container">

    @if(auth()->check())
        <div class="text-right pt-1">
            @if(isset($showAdminLink) && $showAdminLink && auth()->user()->is_admin)
                <a href="{{ route('admin.home') }}" class="d-inline-block">
                    <i class="fa fa-2x fa-cogs"></i>
                </a>
            @endif

            <a href="{{ action('MeetupsController@showSettingForm') }}" class="d-inline-block ml-2">
                <i class="fa fa-2x fa-cog"></i>
            </a>

            <a href="{{ action('MeetupsController@logout') }}" class="d-inline-block ml-2">
                <i class="fa fa-2x fa-power-off"></i>
            </a>
        </div>
    @endif

    @yield('content')

</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"
        integrity="sha256-1A78rJEdiWTzco6qdn3igTBv9VupN3Q1ozZNTR4WE/Y=" crossorigin="anonymous"></script>

@stack('scripts')

</body>
</html>