routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// MEETUPS
Route::get('/', 'MeetupsController@index')->name('home');

Route::get('/get-balance', 'MeetupsController@getBalance');

Route::get('/login', 'MeetupsController@showLoginForm');
Route::post('/login', 'MeetupsController@login');
Route::get('/logout', 'MeetupsController@logout');

Route::get('/setting', 'MeetupsController@showSettingForm');
Route::post('/setting', 'MeetupsController@saveSetting');

Route::get('/subscribe', 'MeetupsController@showSubscribeForm');
Route::post('/subscribe', 'MeetupsController@subscribe');

Route::get('/claim', 'MeetupsController@showClaimForm');
Route::post('/claim', 'MeetupsController@claim');



// ADMIN
Route::middleware(['admin.login'])->namespace('Admin')->prefix('admin_ZwMTBv')->name('admin.')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('user', 'UserController');

    Route::resource('transaction-info', 'TransactionInfoController');
});

app/Models/User.php
<?php

namespace App\Models;

use App\Services\MailChimpService;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Notifications\Notifiable;

class User extends BaseModel implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'password', 'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\EmailFilter;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::query()
//            ->filterWhere('username', '=', $request->input('username'))
//            ->filterWhere('created_at', '>=', $request->input('created_at_from'))
//            ->filterWhere('created_at', '<=', $request->input('created_at_to'))
//            ->orderBy('id', 'DESC')
            ->paginate();

        return view('admin.user.index', [
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'username' => 'required|string|max:255|unique:users',
            'password' => 'required|string',
            'is_admin' => 'boolean',
        ]);

        $user = new User($request->input());
        $user->password = bcrypt($user->password);
        $user->remember_token = str_random(10);
        $user->is_admin = (int)$request->input('is_admin');

        $user->save();

        return response()->redirectToRoute('admin.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('admin.user.edit', ['model' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $this->validate($request, [
            'username' => 'required|string|max:255|unique:users,username,' . $user->id,
            'password' => 'nullable|string',
            'is_admin' => 'boolean',
        ]);

        $user->username = $request->input('username');
        if ($request->has('password')) {
            $user->password = bcrypt($request->input('password'));
        }
        $user->is_admin = (int)$request->input('is_admin');

        $user->save();

        return response()->redirectToRoute('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $user->delete();

        return response()->redirectToRoute('admin.user.index');
    }

    public function massAction(Request $request)
    {
        $ids = $request->input('item_ids', []);
        $act = $request->input('mass_action');

        /** @var User[] $models */
        $models = User::whereIn('id', $ids)->get();

        switch ($act) {
            case 'ban':
                foreach ($models as $model) {
                    $model->is_banned = 1;
                    $model->save();
                }
                break;
            case 'delete':
                foreach ($models as $model) {
                    $model->delete();
                }
                break;
        }

        return response()->redirectToRoute('admin.user.index');
    }

}

resources/views/admin/user/_form.blade.php
{{ isset($model)
 ? Form::model($model, ['route' => ['admin.user.update', $model->id], 'method' => 'PUT'])
 : Form::open(['route' => ['admin.user.store'], 'method' => 'post'])
}}

<div class="form-group">
    <label>
        Username <span class="text-danger">*</span>
    </label>
    {{ Form::text('username', null, ['class' => 'form-control' . ($errors->has('username') ? ' is-invalid' : '')]) }}
    @if ($errors->has('username'))
        <span class="invalid-feedback">{{ $errors->first('username') }}</span>
    @endif
</div>

<div class="form-group">
    <label>
        Password
        @if(isset($model))
            <small class="font-italic">Keep blank if you don't want to change</small>
        @else
            <span class="text-danger">*</span>
        @endif
    </label>
    {{ Form::password('password', ['class' => 'form-control' . ($errors->has('password') ? ' is-invalid' : '')]) }}
    @if ($errors->has('password'))
        <span class="invalid-feedback">{{ $errors->first('password') }}</span>
    @endif
</div>

<div class="form-group">
    <div class="form-check">
        {{ Form::checkbox('is_admin', 1, null, ['class' => 'form-check-input', 'id' => 'checkbox-is_admin']) }}
        <label class="form-check-label" for="checkbox-is_admin">
            is_admin
        </label>
    </div>
</div>

<div class="form-group">
    <button type="submit" class="btn btn-primary">{{ isset($model) ? 'Update' : 'Create' }}</button>
</div>

{{ Form::close() }}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('content')

    <h3>Create new User</h3>

    @include('admin.user._form')

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h3>Update User {{ $model->username }}</h3>

    @include('admin.user._form')

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('content')


    <h3>List Admins</h3>

    <div>
        <form action="{{ route('admin.user.index') }}">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Created between</label>
                        <input type="text" name="created_at_range" value="{{ request('created_at_range') }}"
                               data-input-from="#created_at_from"
                               data-input-to="#created_at_to"
                               class="form-control date-range-picker"/>
                        <input type="hidden" name="created_at_from" id="created_at_from"
                               value="{{ request('created_at_from') }}"/>
                        <input type="hidden" name="created_at_to" id="created_at_to"
                               value="{{ request('created_at_to') }}"/>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Username</label>
                        <input name="username" class="form-control" value="{{ request('username') }}"/>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div>
                            <label>
                                <input type="checkbox" value="1"
                                       name="is_admin" {{ request('is_admin') ? 'checked' : '' }}/>
                                is_admin
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Username</th>
                <th scope="col">is_admin</th>
                <th scope="col">created_at</th>
                <th scope="col" style="width: 114px;">
                    <a href="{{ route('admin.user.create') }}" class="btn btn-success btn-sm btn-block">
                        <i data-feather="plus-square"></i>
                    </a>
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <th scope="row">{{ $user->id }}</th>
                    <td>{{ $user->username }}</td>
                    <td>
                        @if($user->is_admin)
                            <span class="badge badge-success">ADMIN</span>
                        @else
                            <span class="badge badge-primary">user</span>
                        @endif
                    </td>
                    <td>{{ $user->created_at->format('Y-m-d H:i:s') }}</td>
                    <td>

                        <a href="{{ route('admin.user.edit', ['id' => $user->id]) }}" class="btn btn-primary btn-sm">
                            <i data-feather="edit"></i>
                        </a>
                        <button type="button" class="btn btn-sm btn-danger btn-delete"
                                data-confirm="Are you sure want to delete admin: {{ $user->username }}"
                                data-url="{{ route('admin.user.destroy', ['id' => $user->id]) }}">
                            <i data-feather="trash-2"></i>
                        </button>

                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div>
        {{ $users->appends(request()->all())->links('pagination::bootstrap-4') }}
    </div>

@endsection